version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: brickstat-app/backend/Dockerfile
    container_name: brickstat-backend
    env_file:
      - brickstat-app/backend/.env
    ports:
      - "5001:5000"
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
