services:
  backend:
    build:
      context: brickstat-app/backend
      dockerfile: Dockerfile
    image: brickstat-backend
    container_name: brickstat-backend
    env_file:
      - ./.env
    ports:
      - "5010:5000"
    environment:
      - PYTHONUNBUFFERED=1
